export const initialBooks = [
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "978-0743273565",
    genre: "Classic Fiction",
    publish_year: 1925,
    copies_available: 4,
    total_copies: 5,
    spine_color: "#1E3D59",
    cover_style: "leather-navy",
    description: "A portrait of the Jazz Age in all its decadence and excess, Gatsby explores themes of idealism, social upheaval, and the elusive American Dream through the mysterious Jay Gatsby.",
    rating: 4.8,
    is_favorite: true,
    notes: "First edition acquired from the Long Island estate library. Gilded leaf lettering."
  },
  {
    title: "1984",
    author: "George Orwell",
    isbn: "978-0451524935",
    genre: "Dystopian",
    publish_year: 1949,
    copies_available: 3,
    total_copies: 4,
    spine_color: "#8B1E1E",
    cover_style: "leather-crimson",
    description: "A chilling prophecy about the future where Big Brother is always watching. Winston Smith struggles for sanity and liberty under a totalitarian regime that rewrites history.",
    rating: 4.9,
    is_favorite: true,
    notes: "Ministry of Truth archive stamp on interior flyleaf."
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    isbn: "978-0441172719",
    genre: "Science Fiction",
    publish_year: 1965,
    copies_available: 2,
    total_copies: 3,
    spine_color: "#A66D29",
    cover_style: "leather-amber",
    description: "Set on the desert planet Arrakis, Dune tells the story of Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only substance of value is melange spice.",
    rating: 4.9,
    is_favorite: false,
    notes: "Sand-embossed binding with golden imperial crest."
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "978-0141439518",
    genre: "Romance / Classic",
    publish_year: 1813,
    copies_available: 5,
    total_copies: 6,
    spine_color: "#2E5A44",
    cover_style: "leather-emerald",
    description: "Elizabeth Bennet navigates manners, upbringing, morality, and marriage in the society of the landed gentry of early 19th-century England, crossing paths with the haughty Mr. Darcy.",
    rating: 4.7,
    is_favorite: true,
    notes: "Bound in fine emerald morocco with botanical filigree on spine."
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbn: "978-0547928227",
    genre: "Fantasy",
    publish_year: 1937,
    copies_available: 3,
    total_copies: 5,
    spine_color: "#4A3525",
    cover_style: "leather-bark",
    description: "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, until Gandalf the wizard and a company of dwarves whisk him off on an adventure to raid the hoard of Smaug the dragon.",
    rating: 4.9,
    is_favorite: true,
    notes: "Features hand-drawn Thror map in runes inside cover pocket."
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    isbn: "978-0143131847",
    genre: "Gothic Horror",
    publish_year: 1818,
    copies_available: 2,
    total_copies: 2,
    spine_color: "#2C3539",
    cover_style: "leather-obsidian",
    description: "Victor Frankenstein, an ambitious young scientist, creates a sentient creature in an unorthodox scientific experiment, unleashing consequences that unravel his world.",
    rating: 4.6,
    is_favorite: false,
    notes: "Inscribed: 'Beware; for I am fearless, and therefore powerful.'"
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0060935467",
    genre: "Historical Fiction",
    publish_year: 1960,
    copies_available: 4,
    total_copies: 4,
    spine_color: "#5C3A58",
    cover_style: "leather-plum",
    description: "A gripping tale of racial injustice in the American South seen through the innocent eyes of Scout Finch, whose father Atticus defends a Black man falsely accused of a terrible crime.",
    rating: 4.8,
    is_favorite: false,
    notes: "Maycomb County law library seal embossed on corner."
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbn: "978-0062315007",
    genre: "Philosophical Fiction",
    publish_year: 1988,
    copies_available: 5,
    total_copies: 5,
    spine_color: "#8C5828",
    cover_style: "leather-bronze",
    description: "An enchanting fable about following one's Personal Legend, following the Andalusian shepherd boy Santiago on his journey across the Egyptian desert.",
    rating: 4.6,
    is_favorite: false,
    notes: "Illuminated stars and desert dunes gilded on spine ribs."
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    isbn: "978-0143058144",
    genre: "Psychological Fiction",
    publish_year: 1866,
    copies_available: 1,
    total_copies: 3,
    spine_color: "#3F2644",
    cover_style: "leather-violet",
    description: "Raskolnikov, a destitute former student in Saint Petersburg, formulate a theory that extraordinary individuals are above moral law, then struggles with psychological torment after committing murder.",
    rating: 4.7,
    is_favorite: false,
    notes: "Heavy antique tome with deep foil relief."
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    isbn: "978-0141439570",
    genre: "Gothic / Philosophical",
    publish_year: 1890,
    copies_available: 3,
    total_copies: 3,
    spine_color: "#184A45",
    cover_style: "leather-teal",
    description: "Dorian Gray trades his soul so that a portrait will age and bear the marks of his sins while he remains forever young, hedonistic, and handsome.",
    rating: 4.7,
    is_favorite: true,
    notes: "Victorian aesthetic movement gilt ornaments."
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    isbn: "978-0060850524",
    genre: "Dystopian Sci-Fi",
    publish_year: 1932,
    copies_available: 2,
    total_copies: 4,
    spine_color: "#1B3B6F",
    cover_style: "leather-sapphire",
    description: "A world state where citizens are genetically bred, pharmaceutically numbed, and conditioning-controlled in a sterile utopia devoid of suffering and soul.",
    rating: 4.5,
    is_favorite: false,
    notes: "London Central Hatchery archival registration."
  },
  {
    title: "The Odyssey",
    author: "Homer",
    isbn: "978-0140268867",
    genre: "Epic Poetry / Classic",
    publish_year: -700,
    copies_available: 2,
    total_copies: 2,
    spine_color: "#69381A",
    cover_style: "leather-terracotta",
    description: "The ten-year journey of Odysseus, king of Ithaca, as he strives to return home after the fall of Troy, battling mythical monsters and the wrath of gods.",
    rating: 4.8,
    is_favorite: true,
    notes: "Translated in verse; Mediterranean meander pattern stamped on leather borders."
  }
];
